### ISSUE TITLE
!python iNAS/train.py -opt options/train/SOD/train_supernet_sod_4gpu_b10_e100_noaug.yml

### ISSUE THREAD

**Issue by JcccKing** [guyuchao/iNAS#1]
你好,
![图片](https://user-images.githubusercontent.com/46700363/143673640-c45351e9-49fb-4624-9a32-a26b5349dc7d.png)

Traceback (most recent call last):
  File "iNAS/train.py", line 246, in <module>
    train_pipeline(root_path)
  File "iNAS/train.py", line 145, in train_pipeline
    model = build_model(opt)
  File "/output/iNAS/iNAS/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/output/iNAS/iNAS/models/oneshot_model.py", line 40, in __init__
    self.load_network(self.supernet, load_path, self.opt['path'].get('strict_load', True), param_key)
  File "/output/iNAS/iNAS/models/base_model.py", line 245, in load_network
    load_net = load_net[param_key]
KeyError: 'state_dict'
首先这两个文件权重一样吗, 其次 为什么会报这个错呢 按照你的log 文件来弄得

**Comment by guyuchao** [comment]
Hello, the two weight files are different. The checkpoint-28b11d7f.pth is the ImageNet-pretrained weight of our search space. If you need to train our supernet on different devices, you need to load this file. And the supernet_latest_xxx.pth is the trained supernet on Salient Object Detection (SOD) task. If you want to search on SOD, you need to load this file.

**Comment by JcccKing** [comment]
okok, l know. I didn't notice another weight file, thanks. 
Good luck in scientific research
