### ISSUE TITLE
How to generate the pretrain supernet checkpoints

### ISSUE THREAD

**Issue by SuperDickHead** [guyuchao/iNAS#4]
Hello again! I have noticed that you provided your pretrained checkpoints checkpoint-28b11d7f.pth. If i modify the search space,how can i get my checkpoints, and how can i pretrain it? Is the pretrain process including pretraining the supernet backbone on imagenet?  Thank you!

**Comment by guyuchao** [comment]
The pretrain process contains the ImageNet-pretraining (if you modify the search space). But for downstream tasks, like SOD, semantic segmentation, you do not need to pre-train the search space repeatedlly.  I can provide the old code of the imagenet pretraining([Google Drive](https://drive.google.com/file/d/1xXGjZ5eBNQtOPbAl_SLpsrNbQIFAMf_V/view?usp=sharing)), which is not compatible to this codebase. The key idea is to change the transport and decoder part to a searchable classifcation head, and adopt sandwich rule (in BigNAS) to train.

**Comment by SuperDickHead** [comment]
Ok,i see. I may transfer your work to object detection and segmentation tasks.  If i make it, i will thank your work in my 毕业设计 acknowledgement. lol... Thank you very much,your work is significant,and means a lot! By the way, about my last issue.  I think it is the incompatibility of pytorch,not about distributed trainning. I delete the(.module) of  state_dict = self.supernet.module.state_dict() then the validation process don't go wrong. I may contact you again if i encounter other problem! Thank you very much.
