### ISSUE TITLE
some bug about the searching space

### ISSUE THREAD

**Issue by SuperDickHead** [guyuchao/iNAS#6]
I have tried different search space, and i find that sometimes i can't search the kernel in backbone stage1 and stage2,(torch.nn.modules.module.ModuleAttributeError: 'SMSU' object has no attribute 'ks_5' )and the deeper stage kernel in  backbone is searchable. And sometime i can seach the kernel in stage 1,2, I 'm running my first version and it support the kernel seach in backbone stage 1 and 2. I don't know if i express myself clearly,so i say it in Chinese again.
就是我发现搜索空间的cfg里backbone stage1,2有的时候我可以设置kernel 搜索[3,5,7,9],有的时候我只能设置[3]它才不会报错， (torch.nn.modules.module.ModuleAttributeError: 'SMSU' object has no attribute 'ks_5' )，我的第一版搜索只搜索了骨干，之后每个stage的kernel我都可以自由的搜索，第二版我加入了transport的搜索空间，然后导致了我backbone的stage1和2的kernel不能搜了别的都没问题，请问是什么原因呢。

**Comment by guyuchao** [comment]
We fix the kernel search space in stage 1 and stage 2 because large kernels in the first two stages will largely add the computation cost in training.

**Comment by SuperDickHead** [comment]
Did you do this recently?since i haven't update. My input is not big,and i do want to seach kernel in the prior stage,can you tell me how can i undo your fix.
